import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from './index.module.scss';
import FlexHome from './FlexHome';

// const inter = Inter({ subsets: ['latin'] });

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}> */}
      <main className={`${styles.main}`}>
        <FlexHome />
      </main>
    </>
  );
}
